// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7VqoEyeYeE9qF3mYtWLK77v1S4Eu11U',
    appId: '1:835471751124:web:579c2dde193b769fa98841',
    messagingSenderId: '835471751124',
    projectId: 'tubes-mobile-505c0',
    authDomain: 'tubes-mobile-505c0.firebaseapp.com',
    storageBucket: 'tubes-mobile-505c0.appspot.com',
    measurementId: 'G-HZYKWXSRVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtU1aHWmovPw4wv061QjbOVVRJIozf6A',
    appId: '1:835471751124:android:9e61c22b5d06d3bda98841',
    messagingSenderId: '835471751124',
    projectId: 'tubes-mobile-505c0',
    storageBucket: 'tubes-mobile-505c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_hz2JhkDWncZTPRbjI6oEJWXZo71lrQ',
    appId: '1:835471751124:ios:dc56101d92e0ee25a98841',
    messagingSenderId: '835471751124',
    projectId: 'tubes-mobile-505c0',
    storageBucket: 'tubes-mobile-505c0.appspot.com',
    iosBundleId: 'com.example.tubesPpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM_hz2JhkDWncZTPRbjI6oEJWXZo71lrQ',
    appId: '1:835471751124:ios:e912b48d5ba119f5a98841',
    messagingSenderId: '835471751124',
    projectId: 'tubes-mobile-505c0',
    storageBucket: 'tubes-mobile-505c0.appspot.com',
    iosBundleId: 'com.example.tubesPpb.RunnerTests',
  );
}
